# Generated by Django 6.0 on 2026-01-10 19:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon_key', models.CharField(blank=True, default='', max_length=60)),
                ('is_team', models.BooleanField(default=False)),
                ('is_player', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Gameweek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=60)),
            ],
            options={
                'ordering': ['scope', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='player_photos/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('comp_type', models.CharField(choices=[('LEAGUE', 'League'), ('CUP', 'Cup'), ('SUPER_CUP', 'Super Cup')], max_length=20)),
            ],
            options={
                'ordering': ['comp_type', 'name'],
                'unique_together': {('name', 'comp_type')},
            },
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kickoff_at', models.DateTimeField()),
                ('home_total_points', models.IntegerField(default=0)),
                ('away_total_points', models.IntegerField(default=0)),
                ('home_match_points', models.IntegerField(default=0)),
                ('away_match_points', models.IntegerField(default=0)),
                ('is_played', models.BooleanField(default=False)),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='league.gameweek')),
            ],
            options={
                'ordering': ['kickoff_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fixture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='league.fixture')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='league.competition')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='league.division')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='league.group')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='league.season')),
            ],
            options={
                'ordering': ['-season__start_date', 'competition__comp_type', 'division__order', 'group__order'],
                'unique_together': {('season', 'competition', 'division', 'group')},
            },
        ),
        migrations.AddField(
            model_name='gameweek',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameweeks', to='league.scope'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='league.scope'),
        ),
        migrations.CreateModel(
            name='RecordSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biggest_win_margin', models.IntegerField(default=0)),
                ('highest_team_match_score', models.IntegerField(default=0)),
                ('highest_player_score', models.IntegerField(default=0)),
                ('longest_win_streak', models.IntegerField(default=0)),
                ('longest_unbeaten_streak', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('biggest_win_fixture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_biggest_win', to='league.fixture')),
                ('highest_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_highest_player', to='league.player')),
                ('highest_player_score_fixture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_highest_player_fixture', to='league.fixture')),
                ('highest_team_match_fixture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_highest_team_score', to='league.fixture')),
                ('scope', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='league.scope')),
                ('highest_team_match_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_highest_team', to='league.team')),
            ],
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_fixtures', to='league.team'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_fixtures', to='league.team'),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.TextField(blank=True, default='')),
                ('achievement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='league.achievementtype')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='league.player')),
                ('scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='league.scope')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='league.season')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='league.team')),
            ],
            options={
                'ordering': ['-awarded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='league.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='league.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='league.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('match_points', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('form_last5', models.CharField(blank=True, default='', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_standings', to='league.scope')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_standings', to='league.team')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True, default='')),
                ('from_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='league.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='league.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='league.season')),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='league.team')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('HOME', 'Home'), ('AWAY', 'Away')], max_length=4)),
                ('points', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='league.player')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_scores', to='league.result')),
            ],
            options={
                'indexes': [models.Index(fields=['result', 'side'], name='league_play_result__f350d9_idx'), models.Index(fields=['player'], name='league_play_player__7d21d2_idx')],
                'unique_together': {('result', 'side', 'player')},
            },
        ),
        migrations.CreateModel(
            name='PlayerStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('best_match_points', models.IntegerField(default=0)),
                ('average_points', models.FloatField(default=0.0)),
                ('stddev_points', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_standings', to='league.player')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_standings', to='league.scope')),
            ],
            options={
                'indexes': [models.Index(fields=['scope', 'total_points'], name='league_play_scope_i_a388cc_idx')],
                'unique_together': {('scope', 'player')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='gameweek',
            unique_together={('scope', 'number')},
        ),
        migrations.CreateModel(
            name='PowerRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('score', models.FloatField(default=0.0)),
                ('gameweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_rankings', to='league.gameweek')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_rankings', to='league.scope')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_rankings', to='league.team')),
            ],
            options={
                'ordering': ['scope', 'gameweek__number', 'rank'],
                'unique_together': {('scope', 'gameweek', 'team')},
            },
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['scope', 'gameweek'], name='league_fixt_scope_i_313cea_idx'),
        ),
        migrations.AddIndex(
            model_name='fixture',
            index=models.Index(fields=['scope', 'kickoff_at'], name='league_fixt_scope_i_97383b_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['season', 'awarded_at'], name='league_achi_season__85a596_idx'),
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['achievement_type', 'awarded_at'], name='league_achi_achieve_a0c389_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['season', 'team'], name='league_team_season__74d23a_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['season', 'player'], name='league_team_season__349b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='teamstanding',
            index=models.Index(fields=['scope', 'match_points'], name='league_team_scope_i_ef9acf_idx'),
        ),
        migrations.AddIndex(
            model_name='teamstanding',
            index=models.Index(fields=['scope', 'total_points'], name='league_team_scope_i_ccfe84_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teamstanding',
            unique_together={('scope', 'team')},
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['season', 'date'], name='league_tran_season__f4b3a1_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['player', 'date'], name='league_tran_player__74e5b0_idx'),
        ),
    ]
