# Generated by Django 6.0 on 2026-01-12 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='replay_of',
            field=models.ForeignKey(blank=True, help_text='If this is a replay match, link it to the original fixture.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replays', to='league.fixture'),
        ),
    ]
