# Generated by Django 6.0 on 2026-01-12 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_fixture_replay_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallOfFameEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hof_entries', to='league.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hof_entries', to='league.season')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'unique_together': {('season', 'player')},
            },
        ),
    ]
