# Generated by Django 6.0 on 2026-01-12 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_halloffameentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='awarded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
