# Generated by Django 6.0 on 2026-01-12 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_alter_achievement_awarded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='fixture',
            field=models.ForeignKey(blank=True, help_text='Optional: link this award to a specific fixture (match).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='league.fixture'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='opponent_player',
            field=models.ForeignKey(blank=True, help_text='Optional: opponent player for this award.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements_against_player', to='league.player'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='opponent_team',
            field=models.ForeignKey(blank=True, help_text='Optional: opponent team for this award.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements_against_team', to='league.team'),
        ),
        migrations.AddField(
            model_name='halloffameentry',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hof_entries', to='league.team'),
        ),
    ]
