# Generated by Django 6.0 on 2026-01-12 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_achievement_fixture_achievement_opponent_player_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameweek',
            options={'ordering': ['number', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='gameweek',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='gameweek',
            name='scope',
        ),
    ]
